### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by CCKNBC** [beaudar/beaudar#10]
可能由于您的更新，我猜的话，导致了跨域问题，应该不是我网络问题，因为测试过电脑手机
因为本身更换域名问题去查看留言板，顺便更改beaudar.json顺便发现了这个问题
下图为您网站截图
![跨域截图](https://p.sda1.dev/0/ae9cc9a6fe67f60733622c3dc1442afb/QQ截图20201103162323.png)

**Comment by zsdycs** [comment]
感谢反馈，已经修改。
把服务从GitHub Page 切到 阿里云 OSS 对象存储了，没有设置好 HTTP 请求头。
