### ISSUE TITLE
能从 npm 引入使用吗，异步加载脚本形式感觉还是有点慢

### ISSUE THREAD

**Issue by Shimada666** [beaudar/beaudar#102]

**Comment by zsdycs** [comment]
![image](https://user-images.githubusercontent.com/44798353/161779112-7c51446a-feaa-4710-854e-b8948d3b3aed.png)

能使用 npm 托管的只有 client.js，事实上 client.js 其实载入的时间不到100ms，并不慢。

慢的其实是承载评论的站点的 DNS，因为 .org 并不能在国内备案，故不能使用国内的服务器，而且 DNS 用的 Cloudflare 速度也是一般的。

建议直接自己部署在自己的国内服务器上，添加 CDN。目前 beaudar.lipk.org 加载完成速度在 3500ms 左右，如果部署在国内估计速度可以提升到 300ms 左右。

有服务器和域名的话，我可以提供部署的帮助。

**Comment by Shimada666** [comment]
有域名和服务器，请问怎么部署呢？

**Comment by zsdycs** [comment]
> 有域名和服务器，请问怎么部署呢？

可以参考这个 https://www.lipk.org/blog/2020/06/08/run-utterances/
