### ISSUE TITLE
how to use in react

### ISSUE THREAD

**Issue by better-pz** [beaudar/beaudar#104]
how to use in react ?
I am a personal blog built with dumi. The custom page component is written using react. How can I use it

**Comment by better-pz** [comment]
how to use in react ?
I am a personal blog built with dumi. The custom page component is written using react. How can I use it

**Comment by zsdycs** [comment]
@better-pz  可以尝试 [参考这里](https://segmentfault.com/q/1010000012801924) 的方式做。
