### ISSUE TITLE
看到了基于 Github Discussions 的 giscus

### ISSUE THREAD

**Issue by shenweiyan** [beaudar/beaudar#106]
https://github.com/giscus/giscus

可以折叠评论，好像还不错，作者考虑折腾一下吗？

**Comment by zsdycs** [comment]
目前 beaudar 在 [utterances](https://github.com/utterance/utterances) 的基础上开发的，使用的 api 是 Github issue，我也知道 Github Discussions 的 api 会更加适合讨论、评论等场景，但是从 Github issue 转移到 Github Discussions 的改动，对于目前这个项目的实现来说，是巨大的，相当于新开一个项目。所以如果要基于 Github Discussions 实现的话，将会新开一个仓库的。

**Comment by shenweiyan** [comment]
> 目前 beaudar 在 [utterances](https://github.com/utterance/utterances) 的基础上开发的，使用的 api 是 Github issue，我也知道 Github Discussions 的 api 会更加适合讨论、评论等场景，但是从 Github issue 转移到 Github Discussions 的改动，对于目前这个项目的实现来说，是巨大的，相当于新开一个项目。所以如果要基于 Github Discussions 实现的话，将会新开一个仓库的。

明白，感谢
