### ISSUE TITLE
博客文章 与 Issue 映射，可否新增自定义 id 作为 Label 的方式？

### ISSUE THREAD

**Issue by mzlogin** [beaudar/beaudar#107]
参考 [gitalk](https://github.com/gitalk/gitalk#options) 的配置参数 `id` 的实现。

这样可以 Issue 标题使用页面的完整 title，而 id 作为寻找唯一 Issue 的映射依据（给 Issue 加一个 Label 值为 id 值，比如我可以使用 page.url 截 50 字符 作为 id），这样有几点好处：

1. Issues 列表看起来比较美观：

    <img width="1254" alt="image" src="https://user-images.githubusercontent.com/1646590/191695422-ee22b32f-db7d-44f6-9ae2-52cfc144a26a.png">

3. 可以与 gitalk 真.无缝切换，可以不用手动修改任何 Issue；

4. 可以避免其它映射方式带来的一些问题，如：

    我现在是使用 `issue-term="title"` 的方式，但是这样存在的一个问题是如果页面 A 的标题包含页面 B 的标题，而页面 A 创建时间早于页面 B 的话，那页面 B 会直接使用 A 对应的 Issue——这会导致一些混乱。比如：
  
    <img width="775" alt="image" src="https://user-images.githubusercontent.com/1646590/191694811-af0253ef-26d2-4c50-8d15-fbffa793c94b.png">

**Comment by zsdycs** [comment]
已有的 issue ↔️ 文章 映射确实在 `issue-term="title"` 方式时存在匹配错误的问题，这是因为通过 title 搜索 issue 时只能是模糊匹配的，我将会在 `issue-term="title"` 方式映射时增加 lable，作为唯一值。

详情：
1. [搜索 title](https://docs.github.com/cn/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-the-title-body-or-comments)
2. [搜索 label](https://docs.github.com/cn/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-label)

**Comment by zsdycs** [comment]
- [x] 在 issue-term="title" 方式映射时，增加 lable 作为精确匹配值 (可选，以兼容原来没有配置 lable 的用户)

**Comment by zsdycs** [comment]
已经增加了，但是还没在 index.html 中增加配置项。
在使用 `issue-term` 时，将会精确搜索 `issue-label` 配置的 label。

## `issue-term` 有三个可选项

- `issue-term="url"` 页面url
- `issue-term="pathname"` 页面路径
- `issue-term="自定义"`
