### ISSUE TITLE
关于官方已经放弃 master 作为项目分支提醒！

### ISSUE THREAD

**Issue by yakeing** [beaudar/beaudar#11]
缺少 `beaudar.json` 配置
在存储库 **xxx/Blog** 中，`master` 分支下找不到 `beaudar.json`。

获取帮助：关于 Beaudar 的 Q&A

-----

现在的主分支是 `main`  #**官方(github)** 已经放弃 `master` 作为项目分支了！

虽然不知道你是否继续更新但还是提醒你一下！

**Comment by zsdycs** [comment]
谢谢提醒，今晚我调查一下怎么应对。

**Comment by zsdycs** [comment]
@yakeing 已经在 [修改](https://github.com/beaudar/beaudar/commit/aa1936308da26f53443690619894cf0755089034) 了，增加了一个分支的项目，默认为 master 分支。
