### ISSUE TITLE
打开多个带评论的页面后，获取token 400，接口也被限制了

### ISSUE THREAD

**Issue by abnerwei** [beaudar/beaudar#111]
![1665732032043](https://user-images.githubusercontent.com/19216484/195786720-b299f087-456f-45fb-8b83-857a9d99bcfa.png)

**Comment by zsdycs** [comment]
安全的系统都存在限制，而且免费的限制会更多，如果有大量用户请求的需求，请通过源代码自托管，或考虑其他方式实现评论。[查看详情](https://docs.github.com/cn/rest/overview/resources-in-the-rest-api#rate-limiting)
