### ISSUE TITLE
宽度问题

### ISSUE THREAD

**Issue by yuang01** [beaudar/beaudar#112]
大佬，宽度只能最大是 760px吗？

**Comment by zsdycs** [comment]
目前是这样的，`.timeline` 固定了 `max-width: 760px;`。

**Comment by yuang01** [comment]
能不能百分之百呢

**Comment by zsdycs** [comment]
有两点：
1. 对于评论来说 760px 是一个足够的宽度了。太长的宽度初始时会是一个长条的气泡，不美观。
2. 如果设置 100%，不管是对于已有的用户，还是想要使用的用户来说都要设置一个宽度的限制了。
