### ISSUE TITLE
境内网络无法访问了 🥹

### ISSUE THREAD

**Issue by xaoxuu** [beaudar/beaudar#113]
今天发现境内 GitHub 彻底无法访问了，与此同时 beaudar 评论也加载不出来了，不知道是不是同一个原因。

> 但是 giscus 的评论却能正常加载出来

在同一个网络环境下的对比：

| page1 | page2 |
| :-- | :-- |
| <img width="459" alt="image" src="https://user-images.githubusercontent.com/16400144/205906491-17882106-dd9f-438c-a0d0-51301b8e5753.png"> | <img width="465" alt="image" src="https://user-images.githubusercontent.com/16400144/205906468-cb1ebf5d-db98-47db-a31a-ad0c6b664bf8.png"> |

不知道大佬能不能看看怎么办 🥹

**Comment by zsdycs** [comment]
我看着没问题，GitHub目前访问是不怎么稳定的。






------------------ 原始邮件 ------------------
发件人: Mr. X ***@***.***&gt;
发送时间: 2022年12月6日 19:58
收件人: beaudar/beaudar ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [beaudar/beaudar] 境内网络无法访问了 (Issue #113)





 
今天发现境内 GitHub 彻底无法访问了，与此同时 beaudar 评论也加载不出来了，不知道是不是同一个原因。
  
但是 giscus 的评论却能正常加载出来
 对比： page1 | page2

**Comment by xaoxuu** [comment]
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/16400144/205909027-9ab583cc-86fb-4ba4-a42f-6de43631329b.png">

应该是 `api.github.com` 挂掉导致的，这个能做成一个可配置的吗？不知道用 `vercel` 做的 `rewrite` 能不能解决这个问题。

**Comment by zsdycs** [comment]
这个是核心 API，无法配置的。可以转到我自己的境外服务器上代理一下按道理是可以，我有空试试。



------------------ 原始邮件 ------------------
发件人: Mr. X ***@***.***&gt;
发送时间: 2022年12月6日 20:12
收件人: beaudar/beaudar ***@***.***&gt;
抄送: 李鹏坤-执手对影成双 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [beaudar/beaudar] 境内网络无法访问了 凉 (Issue #113)





 

 
应该是 api.github.com 挂掉导致的，这个能做成一个可配置的吗？不知道用 vercel 做的 rewrite 能不能解决这个问题。

**Comment by xaoxuu** [comment]
我刚试了下这个：
```
curl \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer xxx" \
  https://api.github.xaox.cc/repos/xaoxuu/test/issues \
  -d '{"title":"Test","body":"I'\''m having a problem with this.","labels":["bug"]}'
```
<img width="533" alt="image" src="https://user-images.githubusercontent.com/16400144/205910406-5b31bd59-a171-425f-b8a6-cc2fba499bec.png">

能成功，理论上评论也可以。

**Comment by xaoxuu** [comment]
但是我也不确定哪天 vercel 也被墙，那我就没办法了 😭

**Comment by xaoxuu** [comment]
似乎已经恢复了
