### ISSUE TITLE
本地运行报错

### ISSUE THREAD

**Issue by han-suyu** [beaudar/beaudar#114]
在本地运行，请问报下面的错误是什么含义？
![image](https://user-images.githubusercontent.com/52966805/234910511-25ead74a-1c38-414e-b516-631769b2b66c.png)
之前使用utteranc 也是这个错误

**Comment by zsdycs** [comment]
请给出完整的步骤，在报错中的信息显示，你好像是用浏览器直接打开的HTML文件。

如果要获取本地运行的方法，[请点击这里查看指南](https://github.com/beaudar/beaudar/blob/master/CONTRIBUTING.md)
