### ISSUE TITLE
token -error

### ISSUE THREAD

**Issue by wjcroom** [beaudar/beaudar#115]
无法访问此网站检查 api.lipk.org 中是否有拼写错误。

**Comment by zsdycs** [comment]
Beauder 原来的 api 服务确实是由 api.lipk.org 提供的，但是在大概 5 个月前，已经[修改成为 beaudar-api.lipk.org](https://github.com/beaudar/beaudar/commit/fc462613c85c98566e0df3e94dd0faf321c67682)。

**Comment by wjcroom** [comment]
但是我的评论不能获取token，报这个错，在项目提供的博客地址也是一样的出错信息

**Comment by wjcroom** [comment]
高手确认现在没有问题吗？难道我用了旧的缓存本地client脚本》？

**Comment by wjcroom** [comment]
1. 访问，https://lipk.org/blog/2020/05/31/how-to-use-beaudar/
开发人员工具，
console出现如下错误信息
![console error 400](https://wjcroom.github.io/wjcimg/console.png)

Failed to load resource: the server responded with a status of 400 ()
responded with a status of 400 ()：https://beaudar-api.lipk.org/token

2. 在那个页面评论框下点登录github
打开网址https://api.lipk.org/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps ***
并提示错误信息
![](https://wjcroom.github.io/wjcimg/beadulogin.png)

**Comment by wjcroom** [comment]
![](https://wjcroom.github.io/wjcimg/console.png)

**Comment by zsdycs** [comment]
> Failed to load resource: the server responded with a status of 400 ()
> responded with a status of 400 ()：https://beaudar-api.lipk.org/token

这个问题应该是网络问题，可以尝试在浏览器直接访问 [https://beaudar-api.lipk.org](https://beaudar-api.lipk.org) 看是否可以打开页面，显示 alive。

> 登录后回调 api.lipk.org

这个问题修改了，是因为漏了在 Beaudar App 的设置中更新回调地址导致的。

经过测试，目前已经恢复正常了。感谢您的 issue！

**Comment by wjcroom** [comment]
然而无法在这个网页地址留下评论。
这个的下一页可以
https://lipk.org/blog/2020/06/08/run-utterances/

**Comment by zsdycs** [comment]
是可以的，没有问题。

**Comment by wjcroom** [comment]
https://lipk.org/blog/2020/05/31/how-to-use-beaudar/
留不了

**Comment by wjcroom** [comment]
https://lipk.org/blog/2020/06/08/run-utterances/
可以
