### ISSUE TITLE
feature request: math equation support

### ISSUE THREAD

**Issue by cyliu-phy** [beaudar/beaudar#117]
I wonder if it is  possible to add equation rendering like giscus, thanks

**Comment by zsdycs** [comment]
The `markdown` rendering of Beaudar comes from `api.github.com/markdown`. This makes the content of the Beaudar consistent with the display of the GitHub issue.

**Comment by zsdycs** [comment]
For specific specifications, [please refer to here](https://github.github.com/gfm/)

**Comment by cyliu-phy** [comment]
> The `markdown` rendering of Beaudar comes from `api.github.com/markdown`. This makes the content of the Beaudar consistent with the display of the GitHub issue.

But math equation is already supported by GitHub, see https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions

Some examples:
```
inline math $f(x)$
block math $$f(x)$$
```

inline math $f(x)$
block math $$f(x)$$

**Comment by zsdycs** [comment]
Already [supported](https://github.com/beaudar/beaudar/commit/eacef3c4a7d56d939137eab732fd7778421143ec), you can see the effect [here](https://beaudar.lipk.org/).

**Comment by cyliu-phy** [comment]
Thanks! This is of great help for me!
