### ISSUE TITLE
请在默认分支中同时支持 master 和 main

### ISSUE THREAD

**Issue by lishuhang** [beaudar/beaudar#119]
GitHub 之前因为政治正确的缘故将近期新建立的repo的默认分支名称由master改成了main，所以叫这两个名字的都无需在配置中指定分支名。

![image](https://github.com/beaudar/beaudar/assets/49574/80fa4bd8-e93e-42aa-b77c-03bde261ef0c)

默认分支是 main 的不做额外配置就会这样

**Comment by zsdycs** [comment]
main 是 GitHub 的默认分支，master 是 Git 的默认分支，还是按照 Git 的来吧，主要是改为 main 的原因我不是很认同。
