### ISSUE TITLE
自定义 GitHub 头像源

### ISSUE THREAD

**Issue by ocoke** [beaudar/beaudar#14]
GitHub 头像源在国内被 DNS 污染了，无法正常访问。期望可以自定义头像源，使用自建的反向代理。

**Comment by zsdycs** [comment]
@oCoke
这个功能是完全可行的，但是使用反向代理，就意味着要使用云服务器进行部署，目前 Beaudar 使用的是 Cloudflare 的 Workers 服务，这也意味着要改变 Beaudar 的工作方式，这工作量太多了。
