### ISSUE TITLE
降序排序时加载更多的逻辑有点问题

### ISSUE THREAD

**Issue by xaoxuu** [beaudar/beaudar#33]
你好，非常喜欢您的这款评论插件，我在使用中发现了一个问题：

目前有64条评论，当评论排序设置为 `desc `：
1. 第一页应当显示第 55-64 条，而实际显示的是第 61-64 条数据。
2. 点击加载更多，应该继续按降序从最新的时间往前加载一页（即第 45-54 条数据），但实际却是按升序从最老的时间往后加载一页（第 11-20 条数据）。

评论链接： https://xaoxuu.com/wiki/stellar/

**Comment by zsdycs** [comment]
OK，倒序功能没有仔细测试，晚些时候我看下情况

**Comment by zsdycs** [comment]
倒叙状态下，最后一页 issue 数为 issue 总数取余 10，即：*每页 10 条，最后一页的数据与升序状态相同*。

**原由**：按目前 Github issue 的 [REST API](https://docs.github.com/en/rest/reference/issues#list-issue-comments) 倒序状态下，显示最后 10 条数据前端要做很麻烦的处理，当最后一页不足 10 条要取前一页补，然后“加载更多”要加载前两页，第一页要去掉最后一页补的数量…😅

> 点击加载更多，应该继续按降序从最新的时间往前加载一页

这个已经修改，想起来之前是因为想偷懒，感觉也没多少人用得上，就多考虑这个逻辑了。改了后其实感觉好了很多！✨
