### ISSUE TITLE
一些样式方面的建议

### ISSUE THREAD

**Issue by xaoxuu** [beaudar/beaudar#34]
1. GitHub Issues 以前的风格是方形头像，后来进行了不少了细节微调，个人感觉现在的样式比以前的好看很多，希望作者有空能更新一下和现在的 GitHub Issues 风格保持一致。例如：40px圆形头像、新的 icon
2. 手机端屏幕比较窄，和桌面端一样布局会显得很局促，建议和现在的 GitHub Issues 在手机端风格保持一致
3. markdown 标识后面的描述文字，个人感觉可以省略，因为在较窄屏幕上会导致换行，影响美观。由于会 markdown 的人看到 markdown 的图标就知道支持了，而不知道什么是 markdown 的人即使看了【支持 Markdown 编辑】这几个字也并不会比只看到 markdown 的图标多得到什么信息。所以建议直接去掉。

**Comment by zsdycs** [comment]
前两点我采纳了，这两天将会更新这个样式。

但是第三点我将保留原样，因为我觉得让 **“Markdown”** 这个词出现，才能更好的推广和提醒看到的人使用 Markdown。
这可以说是出于私心吧，个人很喜欢 **“Markdown”** 。

**Comment by xaoxuu** [comment]
感谢大佬 🙏

如果说采纳了前2条的话，GitHub在桌面端是显示一个 md 的图标在右下角，在移动端更是连 md 的图标都隐藏了。

附一张 iPhone 12 mini 上的截图，目前是会导致换行，如果想保留这几个字的话建议缩小一下字号：
![IMG_78D0672BFE63-1](https://user-images.githubusercontent.com/16400144/126768846-0c488891-cf26-4285-bc91-a828d64ac9a9.jpeg)

**Comment by xaoxuu** [comment]
大佬厉害啊，这么快就改好了，不过我发现桌面端也变成紧凑型布局的了😅

**Comment by xaoxuu** [comment]
哦，我仔细对比了下，发现变成紧凑型布局这个触发宽度有点宽（760px）导致的，我的主题最宽也不到700px，所以始终是紧凑型。

我测试了GitHub这个触发宽度是 536px 附近，容器宽度小于 536px 才会变成紧凑型布局。

**Comment by zsdycs** [comment]
嗯，[修改](https://github.com/beaudar/beaudar/commit/60ff3d048bc099a6cc5093ca345dec12884f8390)了
