### ISSUE TITLE
一些样式方面的建议（第二批）

### ISSUE THREAD

**Issue by xaoxuu** [beaudar/beaudar#40]
### 1. 右上角这个表情的 icon
![image](https://user-images.githubusercontent.com/16400144/126857088-35001c42-ce67-4fa2-a670-5e51d08b924e.png)

我是挺喜欢这个新 icon 的 😂
```
<svg aria-hidden="true" viewBox="0 0 16 16" version="1.1" data-view-component="true" height="16" width="16" class="octicon octicon-smiley">
    <path fill-rule="evenodd" d="M1.5 8a6.5 6.5 0 1113 0 6.5 6.5 0 01-13 0zM8 0a8 8 0 100 16A8 8 0 008 0zM5 8a1 1 0 100-2 1 1 0 000 2zm7-1a1 1 0 11-2 0 1 1 0 012 0zM5.32 9.636a.75.75 0 011.038.175l.007.009c.103.118.22.222.35.31.264.178.683.37 1.285.37.602 0 1.02-.192 1.285-.371.13-.088.247-.192.35-.31l.007-.008a.75.75 0 111.222.87l-.614-.431c.614.43.614.431.613.431v.001l-.001.002-.002.003-.005.007-.014.019a1.984 1.984 0 01-.184.213c-.16.166-.338.316-.53.445-.63.418-1.37.638-2.127.629-.946 0-1.652-.308-2.126-.63a3.32 3.32 0 01-.715-.657l-.014-.02-.005-.006-.002-.003v-.002h-.001l.613-.432-.614.43a.75.75 0 01.183-1.044h.001z"></path>
</svg>
```

### 2. 姓名标题 16px -> 14px
![image](https://user-images.githubusercontent.com/16400144/126857125-78d09d46-992a-458a-8159-7cd95ce23874.png)

### 3. 标题栏高度 44px -> 38px
个人感觉 beaudar 的标题栏高度还是略高了一些，如果有很多只有一行的评论，标题栏就已经占据了比较大的面积。

GitHub 这个头像是 40px ，标题栏高度应该是 38px ，再加上上下的边框高度，刚好头像和标题栏是等高的，很满足强迫症。

### 4. 表情栏修改建议
目前是这样的：
![image](https://user-images.githubusercontent.com/16400144/126857677-bf23a629-06da-42dd-9577-78d7bef1804d.png)
在移动端是这样的：
![image](https://user-images.githubusercontent.com/16400144/126857688-9211c99d-14f5-45b4-bd94-c9034e81d82b.png)

建议修改成这样：
![image](https://user-images.githubusercontent.com/16400144/126857774-74f93579-d0d8-4d71-a219-7877ada8b0a5.png)
移动端：
![image](https://user-images.githubusercontent.com/16400144/126857811-63b7f53d-c61a-485f-bbf7-129c3af75fab.png)

> 参考的是 GitHub Discussions 页面的样式： https://github.com/volantis-x/hexo-theme-volantis/discussions/583

**Comment by zsdycs** [comment]
看着不错！表情栏修改的这个处理方案我很喜欢，马上提交。

**Comment by xaoxuu** [comment]
大佬真是神速啊👍

**Comment by xaoxuu** [comment]
再说一个GitHub都没注意到的小细节：
![1D3BC1A5-5229-4564-87C1-4531B0D0D12D](https://user-images.githubusercontent.com/16400144/126860087-eaf29403-93ea-4890-ba72-2ad24260fa6f.jpeg)

在边框厚度为1的时候，外边框圆角弧度如果是6，那么内部容器的圆角弧度应该是5，这样才能完美贴合。
