### ISSUE TITLE
加载更多显示的位置不对

### ISSUE THREAD

**Issue by xaoxuu** [beaudar/beaudar#43]
大佬你好我又来提bug了 😅

![IMG_0010](https://user-images.githubusercontent.com/16400144/127738830-351e14f7-705d-43fa-bf7c-a64ca6334def.jpeg)

如图所示，我的关于页面有 41 条评论，那个「加载更多」跑到了第1条和第2条评论中间了。（实测逻辑是对的，隐藏了中间的20条评论，点了之后会加载出来。）

**Comment by zsdycs** [comment]
嗯，这个简单。吃完饭回去我改下逻辑。

**Comment by zsdycs** [comment]
@xaoxuu [修改了](https://github.com/beaudar/beaudar/commit/965591c3080040a3cceb8b52f0aae6146bfa9ebb)，上次忘记测试这个了。😅

**Comment by xaoxuu** [comment]
大佬厉害，更新真快👍

**Comment by xaoxuu** [comment]
大佬，这个问题又出现了，你看我的关于页面
https://xaoxuu.com/about/

![IMG_0017](https://user-images.githubusercontent.com/16400144/128033389-2e56be94-17e6-428b-bdd7-eb1b1fa47e7b.jpeg)

**Comment by zsdycs** [comment]
[请查看这个修改及上下文的逻辑](https://github.com/beaudar/beaudar/commit/965591c3080040a3cceb8b52f0aae6146bfa9ebb) 在尾页小于三页时会多加载一页，即此时加载更多前会有12条，当大于等于三时，则不加载。 即正常情况下加载更多前会有3～12条数据。

**Comment by xaoxuu** [comment]
哦，没问题就行
