### ISSUE TITLE
我有一个大胆的想法。。。

### ISSUE THREAD

**Issue by xaoxuu** [beaudar/beaudar#45]
![IMG_0022](https://user-images.githubusercontent.com/16400144/128214130-2f9ac4b3-537a-410a-b793-b97121cfe925.jpeg)

增加一个配置可以选择只显示issue部分如图所示，不显示评论框但可以通过表情回应。

这个应用场景就是在博客文章中任意位置插入来自issue的段落，使得静态博客变得灵活起来

**Comment by zsdycs** [comment]
这需求太奇怪了……

**Comment by xaoxuu** [comment]
例如可以通过表情回应变成一个无后端的且防刷票的投票插件：博主自己在一个issue里每一条评论写上一种方案，通过beaudar插入到文章里，观众可以通过点👍或👎进行投票。

或者举办一个活动，参与者上传作品到指定的issue，一样可以让观众在博客里直接投票。

或者很多人要的“说说/动态/时间线”功能，也直接可以满足了。

或者用来代替gist（被墙），在issue里插入仓库指定行的代码，渲染效果也很好，可以成为国内使用gist的替代方案。

不过这一切的前提是一个页面内可以同时存在多个beaudar互不影响，否则就和评论冲突了。

> issue很强大，可以实现“评论”以外的很多需求。

**Comment by zsdycs** [comment]
这是个好的创意，但是这功能会让这个软件变得不纯粹。

目前，[“表达”](https://beaudar.lipk.org/) 专注于 “将 issue 转换为博客评论”，如同代码，一个方法，仅做一件事。

这是一方面，我希望这个插件专注于做好博客评论这一件事情上。

另一方面，也是大家都非常关心的，轻量化，快速。所以，添加一个配置，增加一个与评论这件事情无关的显示模式，我并不看好。

我更关心的功能是类似“修改评论”、“markdown 语法快捷按钮”等功能。

![image](https://user-images.githubusercontent.com/44798353/128481249-b42afbc8-aa2e-472e-8af1-df27a3d1625a.png)
![image](https://user-images.githubusercontent.com/44798353/128481300-0d7cc857-b396-4dfe-a058-87fd2a69a25a.png)

**Comment by xaoxuu** [comment]
额那好吧，那大佬有没有计划单独做一个呢

**Comment by zsdycs** [comment]
生命在于折腾，我在折腾别的。😅
