### ISSUE TITLE
关于 Cloudflare 的  Browser Insights 

### ISSUE THREAD

**Issue by inkss** [beaudar/beaudar#46]
您好，似乎 beaudar 使用了 Cloudflare  的 Workers ，但是在访问的过程中，观察到浏览器有如下请求：

```html
<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{...}'>
```

这是一个跟踪器请求，相关文档说明如下：

- [Cloudflare Web Analytics](https://developers.cloudflare.com/analytics/web-analytics)
- [static.cloudflareinsights.com/beacon.min.js Tracker](https://confection.io/trackers/static-cloudflareinsights-com-beacon-min-js)

这似乎违背了 **没有追踪** 这点，建议关闭此功能。

**Comment by zsdycs** [comment]
OK，已更新配置。
