### ISSUE TITLE
希望能加入回复评论的功能

### ISSUE THREAD

**Issue by AutumnKite** [beaudar/beaudar#48]
如题，希望可以快捷地把一个人的评论引用到评论框内并 at 这个人

**Comment by zsdycs** [comment]
这个其实不难实现，先 `TODO` 一下

- [x] 使用 `@` 时气泡显示当前显示评论的所有评论者
- [ ] ~~添加功能按钮 `引用评论`~~

**Comment by zsdycs** [comment]
### 关于”添加‘引用评论’功能按钮“

调查后发现，如果要实现引用评论

1. 需要将 [api](https://docs.github.com/cn/rest/reference/issues#list-issue-comments) 返回的 issue body 转为 markdown 格式
2. 再转换为 markdown 的引用格式，以实现 `引用` 评论

因为转换后的格式是不一定准确的，也没有在 GitHub 找到类似的功能支持，尝试了如 [turndown](https://github.com/mixmark-io/turndown) 这样的格式转换工具（转格式要引用库的话还是算了……）后效果并不理想，所以我看这功能还是算了。😅
