### ISSUE TITLE
现在自带了白色背景色，导致和网站适配出现了困难

### ISSUE THREAD

**Issue by xaoxuu** [beaudar/beaudar#70]
https://xaoxuu.com/about

以前是挺好的，现在发现多了个白色的底色，请问改怎么办呢：

![image](https://user-images.githubusercontent.com/16400144/147236993-67323fe2-53b6-44d6-b6b2-8add812ccdf1.png)

我看把 `body` 里的 `background` 去掉就好了：

![image](https://user-images.githubusercontent.com/16400144/147237087-3e90e5b9-b8d6-4d83-8f42-7f91564f0d1f.png)

**Comment by zsdycs** [comment]
最近在改变 CSS 的构建和结构，这一点没有考虑到，我会尽快解决这个问题的

**Comment by zsdycs** [comment]
@xaoxuu 已经修复了，如果有任何其他问题，请一定要告诉我。❤️

**Comment by xaoxuu** [comment]
大佬解决的真快呀 👍
