### ISSUE TITLE
验证部分回调出问题

### ISSUE THREAD

**Issue by CCKNBC** [beaudar/beaudar#8]
验证部分回调出问题，像我虽然有域名但测试了使用
ccknbc.github.io作为主页，其他仓库名使用不同主题不同根目录，主要是这样链接就变成了
https://ccknbc.github.io/yun/posts/4/
https://ccknbc.github.io/butterfly/posts/4/
那么点击登录是有问题的，不能跳转回我想要的界面，原版就能直接调转,我现在开启双评论试试

**Comment by zsdycs** [comment]
感谢指正！
是因为我在配置 CDN 时，一并把验证的 work 给到 CDN 了，现在还原回去 cloudflare 了。
