### ISSUE TITLE
是否能够加入粤语、繁中等语言选项？

### ISSUE THREAD

**Issue by Hulenkius** [beaudar/beaudar#86]

**Comment by zsdycs** [comment]
是个很好的提议。

我也希望 beaudar 可以有更多的功能，让所有人都可以乐于“表达”。

上周我增加了 “使用 @ 时气泡显示当前显示评论的所有评论者”的功能。

我觉得，使留言可以更加容易是更加重要的，而且以目前的代码来说，让 beaudar 接入多语言，工作量可不小。

有一个比 beaudar 更好用的评论插件 [giscus](https://github.com/giscus/giscus) 可以满足您多语言的需求。

而且使用的是上线时间不久的 [GitHub Discussions](https://docs.github.com/cn/discussions/quickstart)，有很有意思的 API，可以更好的实现评论功能。
