### ISSUE TITLE
UI建议

### ISSUE THREAD

**Issue by xaoxuu** [beaudar/beaudar#93]
大佬，有个不是很重要但是每次看到都有点别扭的点，就是没有表情的时候能不能不显示这个表情区域的容器：

<img width="823" alt="image" src="https://user-images.githubusercontent.com/16400144/152773121-1deb7dfb-56a0-475f-97a4-5616445263fb.png">

**Comment by zsdycs** [comment]
没问题，回头我看一下。

**Comment by xaoxuu** [comment]
感谢大佬 🙏
